version: '3'
services:
  db:
    image: postgres:14.2-alpine
    container_name: demo-postgres-14.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - VIRTUAL_PORT=5432
    ports:
      - "5432:5432"
    networks:
      - demo_default

  demo-web:
    build: .
    command: "./bin/rails server"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - RAILS_ENV=${RAILS_ENV}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - app-storage:/rails/storage
    depends_on:
      - db
      - nginx-proxy
      - letsencrypt
    networks:
      - demo_default
  
  # Vite React app
  secondary:
    build: ./secondary
    command: "yarn dev"
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST_SECONDARY}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - erts:/erts
    depends_on:
      - nginx-proxy
      - letsencrypt
    networks:
      - demo_default
      
  nginx-proxy:
    image: "jwilder/nginx-proxy:latest"
    container_name: "nginx-proxy"
    volumes:
        - "html:/usr/share/nginx/html"
        - "dhparam:/etc/nginx/dhparam"
        - "vhost:/etc/nginx/vhost.d"
        - "certs:/etc/nginx/certs"
        - "/run/docker.sock:/tmp/docker.sock:ro"
    restart: "always"
    networks: 
        - "demo_default"
    ports:
        - "80:80"
        - "443:443"
    environment:
        - DEFAULT_HOST=${DEFAULT_HOST}

  letsencrypt:
      image: "nginxproxy/acme-companion:latest"
      container_name: "letsencrypt-helper"
      volumes:
          - "html:/usr/share/nginx/html"
          - "dhparam:/etc/nginx/dhparam"
          - "vhost:/etc/nginx/vhost.d"
          - "certs:/etc/nginx/certs"
          - "/run/docker.sock:/var/run/docker.sock:ro"
      environment:
          - NGINX_PROXY_CONTAINER=${NGINX_PROXY_CONTAINER}
          - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
          - NGINX_DOCKER_GEN_CONTAINER=${NGINX_DOCKER_GEN_CONTAINER}
          - LETSENCRYPT_TEST=${LETSENCRYPT_TEST}
      restart: "always"
      depends_on:
          - "nginx-proxy"
      networks: 
          - "demo_default"
          
volumes:
  postgres_data: {}
  app-storage: {}
  erts: {}
  html: {}
  vhost: {}
  dhparam: {}
  certs: {}
  nginx: {}

networks:
  demo_default:
